using Behavioral.TemplateMethod.AbstractClassTemplate.Api;

namespace Behavioral.TemplateMethod.UnitTests;

public class PureTemplateMethodChecklistTests
{
    [Test]
    public void BaseClass_OwnsTheSequence()
    {
        var template = new RecordingReportTemplate();

        _ = template.Generate();

        Assert.That(template.Steps, Is.EqualTo(new[] { "Header", "Body", "Footer" }));
    }

    [Test]
    public void Subclasses_OverrideOnlyVariationPoints()
    {
        ReportTemplate template = new SalesReportTemplate();

        var report = template.Generate();

        Assert.That(
            report,
            Is.EqualTo("Sales ReportRevenue, margin, and forecast data.Generated by the reporting pipeline."));
    }

    [Test]
    public void Tests_ConfirmTheOrder_DoesNotChangeAccidentally()
    {
        var template = new RecordingReportTemplate();

        var report = template.Generate();

        Assert.Multiple(() =>
        {
            Assert.That(report, Is.EqualTo("HeaderBodyFooter"));
            Assert.That(template.Steps, Is.EqualTo(new[] { "Header", "Body", "Footer" }));
        });
    }

    [Test]
    public void DerivedClasses_ShouldNotDuplicateTheFullAlgorithm()
    {
        var generateOverride = typeof(RecordingReportTemplate).GetMethod(
            nameof(ReportTemplate.Generate),
            System.Reflection.BindingFlags.Instance |
            System.Reflection.BindingFlags.Public |
            System.Reflection.BindingFlags.DeclaredOnly);

        Assert.That(generateOverride, Is.Null);
    }

    private sealed class RecordingReportTemplate : ReportTemplate
    {
        public List<string> Steps { get; } = new();

        protected override string BuildHeader()
        {
            Steps.Add("Header");
            return "Header";
        }

        protected override string BuildBody()
        {
            Steps.Add("Body");
            return "Body";
        }

        protected override string BuildFooter()
        {
            Steps.Add("Footer");
            return "Footer";
        }
    }
}