namespace Behavioral.TemplateMethod.AbstractClassTemplate.Api;

public abstract class ReportTemplate
{
    public string Generate()
    {
        var content = BuildHeader() + BuildBody() + BuildFooter();
        return IncludeHook() ? content + BuildHook() : content;
    }

    protected abstract string BuildHeader();
    protected abstract string BuildBody();
    protected abstract string BuildFooter();

    protected virtual bool IncludeHook() => false;
    protected virtual string BuildHook() => string.Empty;
}

public sealed class SalesReportTemplate : ReportTemplate
{
    protected override string BuildHeader() => "Sales Report";
    protected override string BuildBody() => "Revenue, margin, and forecast data.";
    protected override string BuildFooter() => "Generated by the reporting pipeline.";
    protected override bool IncludeHook() => true;
    protected override string BuildHook() => " Hook: exported as PDF.";
}

public static class TemplateMethodDemo
{
    public static object Create()
    {
        ReportTemplate report = new SalesReportTemplate();
        return new
        {
            Pattern = "Template Method",
            Report = report.Generate()
        };
    }
}
