namespace Behavioral.TemplateMethod.AbstractClassTemplate.Api;

public abstract class ReportTemplate
{
    public string Generate()
    {
        return BuildHeader() + BuildBody() + BuildFooter();
    }

    protected abstract string BuildHeader();
    protected abstract string BuildBody();
    protected abstract string BuildFooter();
}

public sealed class SalesReportTemplate : ReportTemplate
{
    protected override string BuildHeader() => "Sales Report";
    protected override string BuildBody() => "Revenue, margin, and forecast data.";
    protected override string BuildFooter() => "Generated by the reporting pipeline.";
}

public static class TemplateMethodDemo
{
    public static object Create()
    {
        ReportTemplate report = new SalesReportTemplate();
        return new
        {
            Pattern = "Template Method",
            Variant = "Pure Template Method",
            Report = report.Generate()
        };
    }
}
